### ISSUE TITLE
想请问一下你说的内存泄露的修复是只修复了那块代码，谢谢

### ISSUE THREAD

**Issue by yuhb0303** [XunMengWinter/Now#3]

**Comment by XunMengWinter** [comment]
是直接用Jsoup抓取网页时OkHttp报的警告：W/OkHttpClient: A connection to http://m.zcool.com.cn/ was leaked. Did you forget to close a response body?

实际上，那个修复没修好（Jsoup源码只有才catch时才close response body）。。。
修复那个是因为我RxJava使用不当造成（调用onNext后没有去调onComplete），没有遵守Observer接口调用的规则，现已规范化（onComplete和onError里调用dispose即可）。
